sudo: false
language: python
python:
  - "3.4"
  - "2.7"
  - "pypy"
  
# get some stuff to install
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y iverilog
# not available on travis ubuntu version, need
# to build from source??
#  - sudo add-apt-repository -y ppa:saltmakrell/ppa
#  - sudo apt-get update
#  - sudo apt-get install yosys

# command to install dependencies
install:
  - chmod +x ./scripts/ci/install_myhdl.sh
  - ./scripts/ci/install_myhdl.sh
  - pip install coverage
  - pip install coveralls
  - pip install Pillow
  - pip install .

# run the test, nosetests can be used
script:
   - cd examples
   - py.test -s
   - cd ../test
   - py.test -s

notifications:
  email: false
